server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: demo-gateway-client1
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 60000
    password: mypass

application:
  clients:
    -
      name: demo-gateway-client1
      url: http://localhost:8081
    -
      name: demo-gateway-client2
      url: http://localhost:8082

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
