spring:
  redis:
    database: 0
    host: localhost
    port: 49153
    timeout: 60000
    username: default
    password: redispw
#  h2:
#    console:
#      enabled: true
#      path: /public/h2-console

logging:
  level:
    com.example.demo: DEBUG
    #    reactor.netty: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG