spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 60000
    password: redis

client:
  demo-gateway-client1:
    url: http://localhost:8081
  demo-gateway-client2:
    url: http://localhost:8082

logging:
  level:
    com.example.demo: DEBUG
    #    reactor.netty: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG